apiName: ContractApi
usings:
defaultOperationAttributes:
  - "[Datadog.Trace.Annotations.Trace]"
operations:
  - name: CreateTemplate
    ignore: true
  - name: CancelContract
    ignore: true
  - name: GetContractById
    ignore: true
  - name: GetContractByIdAdmin
    ignore: true
  - name: GetContractEvents
    ignore: true
  - name: GetTemplateEvents
    ignore: true
  - name: GetTermsAndConditions
    ignore: true
  - name: SignContract
    ignore: true
  - name: ApiHealth
    ignore: true
  - name: Ping
    ignore: true
  - name: GeneratePdf
    ignore: true
  - name: ListContractsByFolderId
    ignore: true
  - name: UploadArtifacts
    ignore: true
  - name: PreviewTemplate
    ignore: true
types:
  - name: DateOnly
    replacementName: DateOnly
    ignore: true