apiName: PetApi
usings:
  - "System"
defaultOperationAttributes:
operations:
  - name: ApiHealth
    ignore: true
  - name: Ping
    ignore: true
types:
  - name: NewPet
    replacementName: CreatePetRequest
    ignore: false
serializeQueryParamsAsRawString: true
