apiName: PetApi
usings:
  - "System"
defaultOperationAttributes:
operations:
  - name: ApiHealth
    ignore: true
  - name: Ping
    ignore: true
  - name: FindPets
    customHeadersParameterEnabled: true
types:
  - name: NewPet
    replacementName: CreatePetRequest
    ignore: false
querySerialization:
  serializeAsRawString: true
  typesFormatting:
    DateTime: "yyyy-MM-dd HH:mm:ss.fffK"