name: OpenApiSdkGenerator CI/CD
run-name: OpenApiSdkGenerator - ${{ github.ref_name }}
on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
  pull_request_target:
    types:
      - opened
      - edited
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'    

    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: src/OpenApiSdkGenerator/OpenApiSdkGenerator.csproj

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet nuget push "src/OpenApiSdkGenerator/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json